#!/bin/sh


########################################################
# Configure PATH so that we can access our scripts
PATH=$PATH:~/.config/bspwm/bin:~/.config/polybar/bin



########################################################
# config options
bspc config border_width            1
bspc config top_padding             22
bspc config window_gap              0
bspc config split_ratio             0.53
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          false
bspc config focus_follows_pointer   true

bspc config pointer_action1         move
bspc config pointer_action3         resize_corner

bspc config remove_disabled_monitors false
bspc config remove_unplugged_monitors false



########################################################
# Rules
bspc rule -r *:*
bspc rule -a smplayer state=floating
bspc rule -a MPlayer state=floating
bspc rule -a xine state=floating
bspc rule -a Pavucontrol state=floating
#bspc rule -a Gimp desktop=iii
#bspc rule -a Gimp-2.8 desktop=iii
bspc rule -a Skype desktop=web state=floating
bspc rule -a QtCreator desktop=dev
bspc rule -a GitKraken desktop=git
bspc rule -a XTerm state=floating
#bspc rule -a libreoffice-writer state=tiled
bspc rule -a libreoffice state=tiled
bspc rule -a Gnome-terminal state=floating
bspc rule -a Wine:TeamViewer.exe state=floating desktop = tv
bspc rule -a VisualExcavator state=floating
bspc rule -a VirtualBox state=floating
bspc config external_rules_command "$(which external_rules)"



########################################################
# colors
bspc config focused_border_color "#0e9ffb"
bspc config normal_border_color "#303030"
bspc config active_border_color "#00ff00"
#~ bspc config focused_locked_border_color "#00C7D8"
#~ bspc config normal_locked_border_color "#708D8F"
#~ bspc config active_locked_border_color "#808C8D"
#~ bspc config urgent_border_color "#cb4b16"
#~ bspc config presel_border_color "#cb4b16"



########################################################
########################################################


########################################################
# wm name [useful for some programs]
wmname KDE



########################################################
# Keyboard layouts
setxkbmap -option grp:alt_caps_toggle -layout us,de



########################################################
# Pointer
xsetroot -cursor_name left_ptr &



########################################################
# Screensaver
pkill -SIGKILL gnome-screensaver
xscreensaver -no-splash &



########################################################
# Num lock
numlockx &



########################################################
# sxhkd
killall sxhkd
sxhkd &



########################################################
# Monitors
setup_monitors r
